import { type NextPage } from "next";
import Head from "next/head";

import { RegoForm } from "~/modules/rego";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Tina and Andrew</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex min-h-screen max-w-5xl flex-col items-center bg-background px-4 py-8">
        <RegoForm />
      </main>
    </>
  );
};

export default Home;
